name: Acknowledge incoming publication

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Add a comment to acknowledge publication
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Comment PR if platform BOM has changed
        uses: thollander/actions-comment-pull-request@v3
        if: contains(github.event.head_commit.modified, 'platform-catalog/')
        with:
          message: |
            [ ] - I acknowledge that merging this PR is going to publish the `platform-catalog` BOM.

      - name: Comment PR if test BOM has changed
        uses: thollander/actions-comment-pull-request@v3
        if: contains(github.event.head_commit.modified, 'test-catalog/')
        with:
          message: |
            [ ] - I acknowledge that merging this PR is going to publish the `test-catalog` BOM.